# Generated by Django 4.0.5 on 2022-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_fakecardgame_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakecardgame',
            name='answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fakenews',
            name='answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
