# Generated by Django 4.0.5 on 2022-06-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_fakecardgame_answer_alter_fakenews_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakecardgame',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fakenews',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
